### ISSUE TITLE
Integrate globalization package into Atlas for mutlilanguage support

### ISSUE THREAD

**Issue by ml9951** [ArnholdInstitute/ATLAS#35]

**Comment by ml9951** [comment]
➤ Kyle Landell commented:

[Matt Le](https://app.asana.com/0/385492340119917/385492340119917)[James Faghmous](https://app.asana.com/0/48557109429360/48557109429360)
The existing localization packages were not integrating into the app nicely, and ended up being rather difficult to work with.  I instead wrote a very simple translation package to handle multiple languages in Atlas.  It offers two modes, a language agnostic mode, where a lookup table is defined by id, and a dictionary mode where the translation lookup table is keyed by the English word or phrase.

I think this solution adequately solves our multi-language problem, and we can easily build in additional features such as date and number formatting as they become needed.  A separate public GitHub repo has been created for this component so that it can be shared across any project.

**Comment by klandell** [comment]
Using custom react-rosetta package
